#+TITLE0:    +-----------+-----------+-----------+-----------+-----------+
#+TITLE0:    |     .     | __     __ |    ___    |   ____    |   ____    |
#+TITLE0:    |    / \    | \ \   / / |   ( _ )   |  |  _ \   |  |  _ \   |
#+TITLE0:    |   / _ \   |  \ \ / /  |   / _ \   |  | |_) |  |  | |_) |  |
#+TITLE0:    |  / ___ \  |   \ V /   |  | (_) |  |  |  _ <   |  |  _ <   |
#+TITLE0:    | /_/   \_\ |    \_/    |   \___/   |  |_| \_\  |  |_| \_\  |
#+TITLE0:    |           |           |           |           |           |
#+TITLE0:    +-----------+-----------+-----------+-----------+-----------+
#+TITLE0:    
#+TITLE0:    AV8RR
#+TITLE0:    
#+Title: Cooking @ Rajbhog Studios
#+Author: Rakesh Rathod

The world is full of cooking classes, cooking videos, books, audio, movies, etc. So what makes this worth your time? The Internet has brought many people together ... and it has created a divisions too.

Cooking @ Rajbhog is designed to bring the community together through a shared interest in a healthy, informed food lifestyle. We can eat with regard to many factors including a higher quality of life on this journey. In class, we will bring interesting facts and information to you to address current issues, trends, and best practices.

Can you learn this on your own? Of course you can. We think you will have a more personal experience with our classes - bridging the divide.

Above this page, you will find class content in their respective folders. Visit any folder and feel free to use the information - all content on this site is licensed under the Creeative Commons, open source license.

* Rakbhod Indian Market and Cafe

Our market and cafe have a variety of brands and food categories. As a full fledged grocery store, we stock the basics and we stock special interest items. Come in for the occaisonal Cilantro or Curry Leaves and stay for the a hot cup of masala chai. Order lunch or dinner and shop the market while you wait for our kitchen staff. Enjoy a game on our large, 15 foot television - yeah, it's really that big!
